name: matrix-demo
on:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [12, 14, 16]
    continue-on-error: true
    runs-on: ${{ matrix.os}}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Setup Node.js
        id: cache
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit !== 'true'
        run: npm ci
      - name: Build project
        run: npm run build