name: Reusable workflow
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the artifact files to download
        required: false
        type: string
    outputs:
      workflow-result:
        description: The result of the workflow
        required: false
        type: string
        value: ${{ jobs.print-result.outputs.job-result }}
    # secrets:
    #   GITHUB_TOKEN:
    #     description: Github token
    #     required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files in artifact
        run: ls -l
  print-result:
    runs-on: ubuntu-latest
    outputs:
      job-result: ${{ steps.print.outputs.step-result }}
    steps:
      - name: Print result
        id: print
        run: echo "step-result=success" >> $GITHUB_OUTPUT