name: Reusable workflow
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: The nameo of the artifact files to download
        required: false
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files in artifact
        run: ls -l